[package]
name = "tsp-rustdx-native"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lib]
name = "tsp_rustdx_native"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25" }
rustdx-complete = { git = "https://github.com/jelven007/rustdx.git", rev = "fac771a18cd218c90852254e59b040874d156722" }
serde = "1"
serde_json = "1"
